In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/srcuio/base/main/base.csv',sep= ';',decimal =',')

In [ ]:
df_filter = df[['VENTA',"GAS","EMPAQUE","HONORA","COMISION","ARRIENDO","SEGURO","ASEO","ENERGIA","COMUNICA","PUBLICO","FLETES","PUBLICI","ADECUA"]]

In [ ]:
df_filter.head()

VENTA    GAS  EMPAQUE    HONORA  COMISION  ARRIENDO   SEGURO    ASEO  \
0  7141399.0  125.0      0.0  129169.0       0.0   12965.0  42412.0  7325.0   
1  6414054.0    0.0      0.0   17433.0       0.0   69255.0      0.0  1431.0   
2  6946062.0    0.0      0.0   50797.0       0.0   51591.0  20915.0  1734.0   
3        0.0    0.0      0.0       0.0       0.0       0.0      0.0     0.0   
4  8170342.0    0.0  43072.0   50082.0       0.0  247059.0  63822.0  2091.0   

   ENERGIA  COMUNICA  PUBLICO    FLETES  PUBLICI   ADECUA  
0   6789.0    5747.0   3567.0   22354.0      0.0  61644.0  
1   5938.0    5371.0   1432.0       0.0      0.0  15967.0  
2   7724.0   13709.0   2022.0    2241.0  13351.0  34874.0  
3      0.0       0.0      0.0       0.0      0.0      0.0  
4   8309.0   28179.0   3169.0  348483.0  18728.0  72228.0

In [ ]:
df_filter.isnull().sum()

VENTA       0
GAS         0
EMPAQUE     0
HONORA      0
COMISION    0
ARRIENDO    0
SEGURO      0
ASEO        0
ENERGIA     0
COMUNICA    0
PUBLICO     0
FLETES      0
PUBLICI     0
ADECUA      0
dtype: int64

In [ ]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9779 entries, 0 to 9778
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   VENTA     9779 non-null   float64
 1   GAS       9779 non-null   float64
 2   EMPAQUE   9779 non-null   float64
 3   HONORA    9779 non-null   float64
 4   COMISION  9779 non-null   float64
 5   ARRIENDO  9779 non-null   float64
 6   SEGURO    9779 non-null   float64
 7   ASEO      9779 non-null   float64
 8   ENERGIA   9779 non-null   float64
 9   COMUNICA  9779 non-null   float64
 10  PUBLICO   9779 non-null   float64
 11  FLETES    9779 non-null   float64
 12  PUBLICI   9779 non-null   float64
 13  ADECUA    9779 non-null   float64
dtypes: float64(14)
memory usage: 1.0 MB


In [ ]:
for col in df.columns:
  print(col)
  print(df[col].unique())
  print(df[col].dtypes)
  print('---'*10)

V1
[ 987670  987679  987680 ... 1987651 1987652 1987653]
int64
------------------------------
CORRELA_16
['464' '466' '465' '4711-472' '462' '4751-4752' '4771' '4741-4742' '451'
 '4773' '473' '4772' '454' '453' '4759-4761' '4719']
object
------------------------------
CORRE_9
['464-465' '466-469' '471-472' '462-463' '474 - 475' '476 - 477' '451'
 '473' '453-454']
object
------------------------------
IDOJ1
[ 4 14 11  2  5 99  7  9  3 12 13]
int64
------------------------------
IDAIO
[2005 2002 1982 2000 2012 1999 2008 2010 2003 1988 2004 2007 2011 1998
 2009 1996 2015 2013 1992 1993 1994 1995 1997 2001 1981 1984 1985 1986
 1987 2006 1975 1989 1973 1991 1983 1990 1978 1979 2014 1952 1969 1980
 1972 1964 1977 1974 1955 1966 1970 1960 2016 2017 2018 2020 1946 1967
 1968 1971 1957 1962 1944 1959 1963 1961 1954 1930 1958 1976 1945 1953
 1965 1947 1951 1950 2019   10   12 1940 1956    1 1949 1948 1935 1938
 1939 1928 1942 1941 1932]
int64
------------------------------
CIMREP
[0.00000000e+00

In [ ]:
float_cols = df_filter.select_dtypes('float64').columns

for col in float_cols:
  df_filter[col] = df_filter[col].astype('int64')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [ ]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9779 entries, 0 to 9778
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   VENTA     9779 non-null   int64
 1   GAS       9779 non-null   int64
 2   EMPAQUE   9779 non-null   int64
 3   HONORA    9779 non-null   int64
 4   COMISION  9779 non-null   int64
 5   ARRIENDO  9779 non-null   int64
 6   SEGURO    9779 non-null   int64
 7   ASEO      9779 non-null   int64
 8   ENERGIA   9779 non-null   int64
 9   COMUNICA  9779 non-null   int64
 10  PUBLICO   9779 non-null   int64
 11  FLETES    9779 non-null   int64
 12  PUBLICI   9779 non-null   int64
 13  ADECUA    9779 non-null   int64
dtypes: int64(14)
memory usage: 1.0 MB


In [ ]:
df_filter.head()

VENTA  GAS  EMPAQUE  HONORA  COMISION  ARRIENDO  SEGURO  ASEO  ENERGIA  \
0  7141399  125        0  129169         0     12965   42412  7325     6789   
1  6414054    0        0   17433         0     69255       0  1431     5938   
2  6946062    0        0   50797         0     51591   20915  1734     7724   
3        0    0        0       0         0         0       0     0        0   
4  8170342    0    43072   50082         0    247059   63822  2091     8309   

   COMUNICA  PUBLICO  FLETES  PUBLICI  ADECUA  
0      5747     3567   22354        0   61644  
1      5371     1432       0        0   15967  
2     13709     2022    2241    13351   34874  
3         0        0       0        0       0  
4     28179     3169  348483    18728   72228

In [ ]:
from statistics import mode
mode(df_filter['COMISION'])

0

In [ ]:
for col in df_filter:
  print(col)
  print(df_filter[col].unique())

VENTA
[ 7141399  6414054  6946062 ...  2404270 13974313 26788531]
GAS
[ 125    0  315 ... 2446 4898  700]
EMPAQUE
[    0 43072 15293 ... 55759    37 10552]
HONORA
[129169  17433  50797 ...  38974 141858  25982]
COMISION
[      0   13440   20358 ...   49672  151130 9916812]
ARRIENDO
[ 12965  69255  51591 ... 503607 181556 579838]
SEGURO
[42412     0 20915 ...  4942  1279 41078]
ASEO
[ 7325  1431  1734 ... 36741  3882 28955]
ENERGIA
[ 6789  5938  7724 ... 35602 18646 28618]
COMUNICA
[ 5747  5371 13709 ...  6362 41324 84942]
PUBLICO
[ 3567  1432  2022 ...  5239 12082  1449]
FLETES
[ 22354      0   2241 ...  10850   5108 258434]
PUBLICI
[     0  13351  18728 ...  12862   6373 154957]
ADECUA
[61644 15967 34874 ...  1950 63409 36042]


In [ ]:
for col, por in ((df_filter.isna().sum() / df_filter.shape[0]) * 100).to_dict().items():
  print(f"En la columna '{col}' hace falta el {round(por,4)}% de los datos")

En la columna 'VENTA' hace falta el 0.0% de los datos
En la columna 'GAS' hace falta el 0.0% de los datos
En la columna 'EMPAQUE' hace falta el 0.0% de los datos
En la columna 'HONORA' hace falta el 0.0% de los datos
En la columna 'COMISION' hace falta el 0.0% de los datos
En la columna 'ARRIENDO' hace falta el 0.0% de los datos
En la columna 'SEGURO' hace falta el 0.0% de los datos
En la columna 'ASEO' hace falta el 0.0% de los datos
En la columna 'ENERGIA' hace falta el 0.0% de los datos
En la columna 'COMUNICA' hace falta el 0.0% de los datos
En la columna 'PUBLICO' hace falta el 0.0% de los datos
En la columna 'FLETES' hace falta el 0.0% de los datos
En la columna 'PUBLICI' hace falta el 0.0% de los datos
En la columna 'ADECUA' hace falta el 0.0% de los datos


In [ ]:
import numpy as np
import scipy.stats as st
from scipy.spatial.distance import mahalanobis
mahal_distances = []

for row in df_filter.to_numpy():
  mahal_distances.append(mahalanobis(row, df_filter.mean(), np.linalg.inv(np.cov(df_filter.values.T))))

In [ ]:
k = df_filter.shape[0]

df_filter['mahal_distances'] = mahal_distances
df_filter['p_value'] = 1 - st.chi2.cdf(df_filter['mahal_distances'], k-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [ ]:
df_filter = df_filter[df_filter['p_value'] > 0.05]


In [ ]:
df_filter.drop(columns=['mahal_distances','p_value'],inplace=True)


In [ ]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9779 entries, 0 to 9778
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   VENTA     9779 non-null   int64
 1   GAS       9779 non-null   int64
 2   EMPAQUE   9779 non-null   int64
 3   HONORA    9779 non-null   int64
 4   COMISION  9779 non-null   int64
 5   ARRIENDO  9779 non-null   int64
 6   SEGURO    9779 non-null   int64
 7   ASEO      9779 non-null   int64
 8   ENERGIA   9779 non-null   int64
 9   COMUNICA  9779 non-null   int64
 10  PUBLICO   9779 non-null   int64
 11  FLETES    9779 non-null   int64
 12  PUBLICI   9779 non-null   int64
 13  ADECUA    9779 non-null   int64
dtypes: int64(14)
memory usage: 1.1 MB


In [ ]:
df_filter.describe()


VENTA           GAS       EMPAQUE        HONORA      COMISION  \
count  9.779000e+03  9.779000e+03  9.779000e+03  9.779000e+03  9.779000e+03   
mean   3.153376e+07  1.899763e+03  4.137736e+04  2.361457e+05  7.295686e+04   
std    1.766636e+08  2.907671e+04  3.599422e+05  2.193322e+06  1.265200e+06   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    2.418040e+06  0.000000e+00  0.000000e+00  1.065700e+04  0.000000e+00   
50%    6.424641e+06  0.000000e+00  0.000000e+00  3.322400e+04  0.000000e+00   
75%    1.680436e+07  7.500000e+01  5.222500e+03  1.024325e+05  0.000000e+00   
max    5.354490e+09  1.316418e+06  1.363248e+07  1.771441e+08  8.393772e+07   

           ARRIENDO        SEGURO          ASEO       ENERGIA      COMUNICA  \
count  9.779000e+03  9.779000e+03  9.779000e+03  9.779000e+03  9.779000e+03   
mean   3.226929e+05  5.146548e+04  7.524331e+04  1.324865e+05  5.403672e+04   
std    1.852706e+06  2.974315e+05  1.133480e+06  1.845532e+06  3.371079e+05   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    7.000000e+03  1.566500e+03  8.000000e+02  5.403500e+03  4.369000e+03   
50%    5.620200e+04  9.890000e+03  3.856000e+03  1.544400e+04  1.185700e+04   
75%    1.761540e+05  3.091150e+04  1.536500e+04  4.241050e+04  2.932300e+04   
max    6.946715e+07  1.255836e+07  5.685643e+07  7.213894e+07  1.417559e+07   

            PUBLICO        FLETES       PUBLICI        ADECUA  
count  9.779000e+03  9.779000e+03  9.779000e+03  9.779000e+03  
mean   1.196926e+04  3.650241e+05  3.024914e+05  1.403292e+05  
std    1.111932e+05  2.809433e+06  3.222036e+06  8.786452e+05  
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    1.212000e+03  1.691500e+03  0.000000e+00  4.325500e+03  
50%    2.870000e+03  2.516300e+04  1.521000e+03  2.174000e+04  
75%    6.494000e+03  1.366740e+05  1.628150e+04  7.293400e+04  
max    4.640087e+06  1.192237e+08  1.013593e+08  2.729177e+07